name: test on iOS simulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.11
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
      - name: Prepare Simulator
        run: |
          xcrun simctl boot "iPhone 12 Pro" || true
          open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: Experiments.xcodeproj
          scheme: Experiments
          result-bundle-path: test-results/all-tests
          destination: 'platform=iOS Simulator,name=iPhone 12'
      - name: Remove symbolic link created by Xcode
        if: always()
        run: rm test-results/all-tests || true
      - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/243
        if: always()
        run: zip -FSry results.zip test-results || true
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.zip
