name: test on iOS simulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
      - name: Prepare Simulator
        run: |
          xcrun simctl create iphone-12-pro "iPhone 12 Pro"
          xcrun simctl boot iphone-12-pro
          open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@master
        with:
          action: build-for-testing
          project: Experiments.xcodeproj
          scheme: Experiments
          destination: name=iphone-12-pro
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@master
        with:
          action: test-without-building
          result-bundle-path: test-results/all-tests
          project: Experiments.xcodeproj
          scheme: Experiments
          destination: name=iphone-12-pro
      - name: Remove symbolic link created by Xcode
        if: always()
        run: rm test-results/all-tests || true
      - name: Archive results # due to: https://github.com/actions/upload-artifact/issues/243
        if: always()
        run: zip -FSry results.zip test-results || true
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.zip
